### ISSUE TITLE
Internal Server Error on Follower CRUD Command

### ISSUE THREAD

**Issue by FHanko** [paenko/PaenkoDb#4]
Backtrace Follower:

> root@Paenko-ubuntu-1gb-fra1-01:~# RUST_BACKTRACE=1 ./document29458 server config                                                                                                             t2.toml
Init "303ff902-ae8e-455d-aa4a-cf9ca5cb8c33"
Init "3e139f55-ba0b-4cf3-abd2-528df5d670a6"
[Uuid("e67d1e05-59bc-4325-a1d6-3885415972ee"), Uuid("137e8977-c550-476e-b869-daa                                                                                                             85a31b56f"), Uuid("d28437f8-d5af-464c-8b65-18646604ae02"), Uuid("f8d5b777-b126-4                                                                                                             c6a-b785-acd920d9f0ca"), Uuid("eb493e05-13cb-4f48-b59a-65086a25118e")]
thread '<unnamed>' panicked at 'LeaderSearchExhausted', /home/flo/host/Semester/                                                                                                             PaenkoDb/src/document/src/handler.rs:92
stack backtrace:
   1:     0x55c68bd5219c - std::sys::imp::backtrace::tracing::imp::write::hf7294                                                                                                             f5e24536b4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c68bd55d6e - std::panicking::default_hook::{{closure}}::h9a07d0b00                                                                                                             c43fbee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:351
   3:     0x55c68bd55974 - std::panicking::default_hook::hf25feff2d08bf39b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:367
   4:     0x55c68bd5620b - std::panicking::rust_panic_with_hook::h4cb8c6fbb8386c                                                                                                             cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:555
   5:     0x55c68bd560a4 - std::panicking::begin_panic::heb3517ba798e470b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:517
   6:     0x55c68bd55fc9 - std::panicking::begin_panic_fmt::h7bf5635a07d66272
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:501
   7:     0x55c68b8c8b2a - document::handler::Handler::post::h262c55dbf2ccf45b
                        at /home/flo/host/Semester/PaenkoDb/src/document/src/han                                                                                                             dler.rs:92
   8:     0x55c68b8c5e84 - document::http_handler::init::http_post::h68a3960e497                                                                                                             27031
                        at /home/flo/host/Semester/PaenkoDb/src/document/src/htt                                                                                                             p_handler.rs:277
   9:     0x55c68b8c3683 - document::http_handler::init::{{closure}}::hbb712a1e7                                                                                                             ad0e187
                        at /home/flo/host/Semester/PaenkoDb/src/document/src/htt                                                                                                             p_handler.rs:60
  10:     0x55c68b78f1a3 - <F as iron::middleware::Handler>::handle::hdf194328a4                                                                                                             6b7d13
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/iron-0.5.1/src/middleware/mod.rs:312
  11:     0x55c68bad27e0 - <alloc::boxed::Box<iron::middleware::Handler + 'stati                                                                                                             c> as iron::middleware::Handler>::handle::hc20d4fda27881fa8
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/iron-0.5.1/src/middleware/mod.rs:318
  12:     0x55c68ba8b6c5 - router::router::Router::handle_method::he4714cdc2ece7                                                                                                             96f
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/router-0.5.1/src/router.rs:199
  13:     0x55c68ba8ba16 - <router::router::Router as iron::middleware::Handler>                                                                                                             ::handle::h9a030b2caeb7fe04
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/router-0.5.1/src/router.rs:212
  14:     0x55c68b868f98 - <iron::iron::RawHandler<H> as hyper::server::Handler>                                                                                                             ::handle::hca329e58ad139bd3
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/iron-0.5.1/src/iron.rs:176
  15:     0x55c68b75403c - <hyper::server::Worker<H>>::keep_alive_loop::hba11381                                                                                                             a240ac0a2
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/hyper-0.10.4/src/server/mod.rs:341
  16:     0x55c68b754c13 - <hyper::server::Worker<H>>::handle_connection::h83d0b                                                                                                             ef913ee281e
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/hyper-0.10.4/src/server/mod.rs:287
  17:     0x55c68b822b77 - hyper::server::handle::{{closure}}::hc6887829b270a0a5
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/hyper-0.10.4/src/server/mod.rs:246
  18:     0x55c68b823039 - hyper::server::listener::spawn_with::{{closure}}::h32                                                                                                             faf6e6e31b3ee0
                        at /home/flo/.cargo/registry/src/github.com-1ecc6299db9e                                                                                                             c823/hyper-0.10.4/src/server/listener.rs:50
  19:     0x55c68b8a87c4 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce                                                                                                             <()>>::call_once::h9c70f4ccfc7a91e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panic.rs:296
  20:     0x55c68b775dde - std::panicking::try::do_call::hbe79c00dea4a1be1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:460
  21:     0x55c68bd5d16a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libpanic_unwind/lib.rs:98
  22:     0x55c68b775374 - std::panicking::try::h61059069f1e1a464
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panicking.rs:436
  23:     0x55c68b771da2 - std::panic::catch_unwind::h921ac8b1fceda254
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/panic.rs:361
  24:     0x55c68b7742a5 - std::thread::Builder::spawn::{{closure}}::hcce5d8ee07                                                                                                             7aac4d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/thread/mod.rs:357
  25:     0x55c68b7e1fa4 - <F as alloc::boxed::FnBox<A>>::call_box::hb08b2a49d05                                                                                                             b0d0b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/liballoc/boxed.rs:614
  26:     0x55c68bd550a4 - std::sys::imp::thread::Thread::new::thread_start::hc1                                                                                                             6926852e47c008
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-li                                                                                                             nux/build/src/libstd/sys/unix/thread.rs:84
  27:     0x7fc78d81e6b9 - start_thread
  28:     0x7fc78d33e82c - clone
  29:                0x0 - <unknown>

Config Leader:
> [server]
node_id = 1
node_address = "127.0.0.1:9000"
rest_port = 3000
binding_addr = "207.154.216.94:3000"
community_string = "AAA"
volume = "data"
[[peers]]
node_id = 2
node_address = "127.0.0.1:9001"
[[logs]]
lid = "303ff902-ae8e-455d-aa4a-cf9ca5cb8c33"
path = "data"
[[logs]]
lid = "3e139f55-ba0b-4cf3-abd2-528df5d670a6"
path = "data"

Config Follower:
> [server]
node_id = 2
node_address = "127.0.0.1:9001"
rest_port = 3001
binding_addr = "207.154.216.94:3001"
community_string = "AAA"
volume = "data2"
[[peers]]
node_id = 1
node_address = "127.0.0.1:9000"
[[logs]]
lid = "303ff902-ae8e-455d-aa4a-cf9ca5cb8c33"
path = "data"
[[logs]]
lid = "3e139f55-ba0b-4cf3-abd2-528df5d670a6"
path = "data"

**Comment by kper** [comment]
It seems like that the follower cannot find the leader.
Can you try to use the same IP for node_address and binding_addr?

Hint:
Be careful when you use the `path="data"` on all nodes. You will encounter some errors when you want to delete a document because they all operate on the same folder.

**Comment by FHanko** [comment]
Using the same IP address for node_adress and binding_addr fixed the issue.

Thanks!
